services:
  - type: web
    name: taskflow-app
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: LOCAL_MONGODB_URI
        value: ""
      - key: SESSION_SECRET
        generateValue: true
